version: '3.3'

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./traefik.yaml:/etc/traefik/traefik.yaml
    deploy:
      placement:
        constraints: [node.role==manager]
        
  nexus:
    image: sonatype/nexus3
    volumes:
      - ${VOL_BASE_DIR}/nexus:/nexus-data
    labels:
      - "traefik.enable=true"
    # Routers
      # Nexus
      - "traefik.http.routers.nexus.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nexus.service=nexus"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.tls.certresolver=myresolver" 
      # Docker Registry
      - "traefik.http.routers.nexusDocker.rule=Host(`${REGISTRY_DOMAIN_NAME}`)"
      - "traefik.http.routers.nexusDocker.service=nexusDocker"
      - "traefik.http.routers.nexusDocker.entrypoints=websecure"
      - "traefik.http.routers.nexusDocker.tls.certresolver=myresolver"
    # Services
      # Nexus
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
      # Docker Registry
      - "traefik.http.services.nexusDocker.loadbalancer.server.port=5000" 

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role==manager]
        
volumes:
  nexus-volume:
