version: '3.3'

services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - nexus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    networks:
      - nexus
    ports:
      - 8081:8081
    environment:
      - INSTALL4J_ADD_VM_PARAMS="-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g  -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    volumes:
      - nexus-volume:/nexus-data
    labels:
      - traefik.port=8081
      - traefik.http.routers.nexus.rule=Host(`${DOMAIN}`)

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nexus-volume:

networks:
  nexus:
