################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenge HTTP
################################################################
certificatesResolvers:
  nexusresolver:
    acme:
      email: kin3303@gmail.com
      storage: acme.json
      tlsChallenge: true
  registryresolver:
    acme:
      email: daeung@plateer.com
      storage: acme.json
      tlsChallenge: true
