################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenge HTTP
################################################################
#certificatesResolvers:
#  myresolver:
#    acme:
#      caserver: https://acme-staging-v02.api.letsencrypt.org/directory
#      email: your-email@abc.com
#      storage: acme.json
#      httpChallenge:
#        entryPoint: web
certificatesResolvers:
  myresolver:
    acme:
      email: your_email@example.com  
      storage: acme.json
      tlsChallenge: true
        # # used during the challenge
        # entryPoint: web
