apiVersion: v1
kind: Template
labels:
  template: cloudbees-cd-pipline
  xpaas: 1.3.2
metadata:
  name: ${APPLICATION_NAME}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata: 
	name: ${APPLICATION_NAME} 
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
  labels:
    app: nodejs-ex
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: '${APPLICATION_NAME}:{TAG_NAME}'
    runPolicy: Serial
    source:
      git:
        ref: dockerPlugin
        uri: 'https://github.com/kin3303/DDI_OPENSHIFT.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'nodejs:8'
          namespace: openshift
      type: Source
    triggers:
      - generic:
          secret: e30cdd272360ccdb
        type: Generic 
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
          - image: '${APPLICATION_NAME}:{TAG_NAME}'
            imagePullPolicy: Always
            name: ${APPLICATION_NAME}
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - imageChangeParams:
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            name: '${APPLICATION_NAME}:${TAG_NAME}' 
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}  
  spec:
    clusterIP: 172.30.172.67
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP 
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nodejs-ex
    name: nodejs-ex
  spec:
    host: ${APPLICATION_NAME}-${PROJECT_NAME}.${HOST_NAME}.xip.io
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None 
parameters:
- description: The host name for the application.
  name: HOST_NAME
  required: true
  value: 34.69.214.143
- description: The project name for the application.
  name: PROJECT_NAME
  required: true
  value: my-dev
- description: The app name for the application.
  name: APPLICATION_NAME
  required: true
  value: nodejs-demo
- description: The tag name for the application.
  name: TAG_NAME
  required: true
  value: latest
