version: '3.7'

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./traefik.yaml:/etc/traefik/traefik.yaml
    deploy:
      placement:
        constraints: [node.role==manager]

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    labels:
      - "traefik.enable=true"
    # Routers
      - "traefik.http.routers.vault.rule=Host(`vault.letsgohomenow.com`)"
      - "traefik.http.routers.vault.service=nexus"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls.certresolver=myresolver" 
    # Services
      - "traefik.http.services.nexus.loadbalancer.server.port=8200"

  consul:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
      - ./consul/data:/consul/data
    labels:
      - "traefik.enable=true"
    # Routers
      - "traefik.http.routers.consul.rule=Host(`consul.letsgohomenow.com`)"
      - "traefik.http.routers.consul.service=nexusDocker"
      - "traefik.http.routers.consul.entrypoints=websecure"
      - "traefik.http.routers.consul.tls.certresolver=myresolver2"
    # Services
      - "traefik.http.services.nexusDocker.loadbalancer.server.port=8500"

  consul-worker:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -server -join consul -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
    depends_on:
      - consul

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role==manager]
